### PR TITLE
Rename IntLiteral to WholeNumberLiteral

### PR DESCRIPTION
**Pull request by Pancakem**
# Terms

> THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE TERMS OF THE CCLA DATED 2017-11-07 WITH FINOS/LINUX FOUNDATION (FORMERLY THE SYMPHONY SOFTWARE FOUNDATION CCLA).
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Comment by AttilaMihaly** [comment]
Thank you for your contribution @Pancakem. We are ready to merge your PR as soon as you sign the CLA as described above. Let us know if we can help with anything!

**Comment by Pancakem** [comment]
Hey. I did read the terms. I'm stuck on where or how to sign. It would be really great to get help on that. I plan on doing more contributions.

**Comment by maoo** [comment]
Hi @Pancakem , thanks for your contribution!

In order to sign a CLA with FINOS, you'd need to follow instructions on https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-RequirementsforContributions . If you're self-employed, please sign our Individual CLA; if you're employed, we'd need to sign a Corporate CLA with your employer; please send a signed copy of the CLA to secretary@finos.org ; from there, in 1/2 working days we can register you in our systems and re-summon this PR.

Please note that this process only applies to the first contribution; all future contributions will be automatically validated and approved (at least from a CLA standpoint).

Hope this helps! If you have further questions, feel free to email help@finos.org .

**Comment by Pancakem** [comment]
Hello again, I signed the Individual CLA a week ago now. I have not had any feedback yet.

**Comment by AttilaMihaly** [comment]
@maoo, can you please check if @Pancakem is set up already? Do we need to rerun the CLA check somehow?

**Comment by maoo** [comment]
> @maoo, can you please check if @Pancakem is set up already? Do we need to rerun the CLA check somehow?

Hi @AttilaMihaly ! I can't find him in our systems. Could you please send his info (corporate email address, github username, affiliation and link to this PR) to help@finos.org ? I'll take care of re-summoning the bot when it's all done.

TY!

**Comment by AttilaMihaly** [comment]
Hey @Pancakem, you sent the signed ICLA to secretary@finos.org, right?

**Comment by Pancakem** [comment]
Hey @AttilaMihaly . Yes, I sent it there.

**Comment by AttilaMihaly** [comment]
@maoo, @Pancakem already sent all that info to secretary@finos.org. This is an Individual CLA so the process is probably different from corporate ones. Can you check where it got stuck?

**Comment by maoo** [comment]
@cla-bot[bot] check

**Comment by maoo** [comment]
Apologies for the late reply! 

@Pancakem - thanks so much for your contribution! Please let me know if you have any questions re. CLA and FINOS in general.

@AttilaMihaly - feel free to proceed with the merge.

Thank you!

**Comment by AttilaMihaly** [comment]
Thank you for your contribution @Pancakem! And thank you for your patience! It will be much smoother next time now that you went through the CLA process.

**Pull request merged**
