### PR TITLE
Allow gen file to be included in the package

### LINKED ISSUE #131: Morphir elm gen command doesn't work
Running this command

`morphir-elm gen -i ./morphir_ir.json` gives back:

error: morphir-elm-gen(1) does not exist, try --help

Debugging it a bit reveals `morphir-elm-gen.js` is not included in the bundled contents of the package because its not in the "files" property in package.json

### PR DESCRIPTION
**Pull request by aszenz**
Fixes #131

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is accepted successfully, we ask all our open source contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement).

Having reviewed our contributor list, we require a CLA for the following people : (@aszenz).

If you need help obtaining a CLA, please read the [Requirements for Contributions](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) section of our CLA wiki or email [help@finos.org](mailto:help@finos.org) with your questions.

Thanks once again for your contribution. Let us work with you to make the CLA process quick, easy and efficient so we can move forward with reviewing and accepting your pull request.

_cc_ **@finos-admin**

**Comment by AttilaMihaly** [comment]
@aszenz, thank you for your contribution! I'll be happy to merge your PR when you find time to sign the CLA. Please note, this is a CLA for finos so you only need to sign it once and you'll be able to contribute to any finos projects.

**Comment by aszenz** [comment]
@AttilaMihaly Thanks I sent the signed cla pdf yesterday to secretary@finos.org from my GitHub email but haven't recieved a reply so far.

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Comment by maoo** [comment]
@AttilaMihaly @aszenz - all checks have passed, the PR can be merged. Thanks for your help!

**Pull request merged**
