### PR TITLE
Creating and testing issues #819 (transpilation of List.sum)  ,  #820 (transpilation of List.length) and TestNameMaxiumum (a function that finds the item in a list which is lowest in alphabetical order)

### PR DESCRIPTION
**Pull request by fjabeen02**
# Terms

> THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE TERMS OF THE CCLA DATED 2017-11-07 WITH FINOS/LINUX FOUNDATION (FORMERLY THE SYMPHONY SOFTWARE FOUNDATION CCLA).
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Comment by jonathanmaw** [comment]
Can you rewrite your commit message and the PR's description?

It would be nice for them to include a brief summary of what #819 and #820 are, and I think you've included commit messages that describe commits that fix previous commits in your working branch, rather than describing what the final commit does (i.e. all the lines starting with "fixing" don't seem to be describing fixes to the codebase)

**Comment by jonathanmaw** [comment]
Also, I don't think the commit message mentions the creation of `testnameMaximum`
(and while you're there, could you rename it from `testnameMaximum` to `testNameMaximum` so that it matches the other function names?

**Comment by jonathanmaw** [comment]
The CI is currently failing at https://github.com/finos/morphir-elm/runs/7538948202?check_suite_focus=true#step:11:173

This *seems* to be that it's confused the Antique type defined in `tests-integration/reference-model/src/Morphir/Reference/Model/Sample/DataDefinition/Persistence/Income/AntiqueShop.elm` with the Antique this code actually uses, at `tests-integration/spark/model/src/SparkTests/Types.elm`

I don't know why it's happening, though.

**Comment by jonathanmaw** [comment]
This PR currently has a commit merging master against itself, and needs to be rebased instead.
I've discussed this with Fatima over IRC, and a branch that has been rebased is coming soon.

**Comment by jonathanmaw** [comment]
These changes all look good to me, and I've confirmed they work locally as well as in CI

**Review by AttilaMihaly — APPROVED** [review]

**Pull request merged**
