### PR TITLE
Import Antiques example into the spark model, add Elm and Spark tests for Antiques model rules

### PR DESCRIPTION
**Pull request by rdale**
Add 'AntiqueSubset' type for use in FunctionTests

# Terms

> THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE TERMS OF THE CCLA DATED 2017-11-07 WITH FINOS/LINUX FOUNDATION (FORMERLY THE SYMPHONY SOFTWARE FOUNDATION CCLA).
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Comment by rdale** [comment]
The pull request copies the Antique Shop model into the Spark tests directory.

It wasn't possible to remove the sources from the reference model because:

  * The type Reference/Model/Sample/DataDefinition/Field/Category.elm is used by the GroceryStore model, although the categories look to be about Antiques and another grocery-specific Category type should probably be created.
  * At the top level the Reference/Model/Sample/DataDefinition/Action.elm type references the Antique type as well as the other two types of shops in the models

**Comment by rdale** [comment]
I've changed the pull request to move all the models under 'Sample' in the reference model to the Spark tests area now

**Comment by jonathanmaw** [comment]
These changes mostly make sense to me.
Do I understand correctly that the process for creating new tests is now:
* Write a test file in tests-integration/spark/elm-tests/tests/
* Add a new entry to create_csv_files.sh
* Add a new test in tests-integration/spark/test/src/AntiqueRulesTests.scala

There seems to be a lot of duplicated code in most of the test files, is it possible to (for example) store some common functions and call those in a `TestUtils.elm`?
Also, what do the sed expressions in create_csv_files.sh do?

**Comment by jonathanmaw** [comment]
Rebased and fixed conflicts with main.

**Review by AttilaMihaly — APPROVED** [review]
This looks like a good solution that we can build more tests on. It could do more around comparing expected outputs and requiring less boilerplate for each new test but we can add those later. This is a great first step.

**Pull request merged**
