### PR TITLE
more sophisticated HTTP error display

### PR DESCRIPTION
**Pull request by bekand**
# Terms

> THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE TERMS OF THE CCLA DATED 2017-11-07 WITH FINOS/LINUX FOUNDATION (FORMERLY THE SYMPHONY SOFTWARE FOUNDATION CCLA).
>
> THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Comment by AttilaMihaly** [comment]
Can you add a screenshot please?

**Comment by bekand** [comment]
image
image

**Comment by bekand** [comment]
image
image

**Comment by AttilaMihaly** [comment]
The popup definitely looks better. Can you put a title on the window, add some description like "The following error happened while processing a response from the server:" and also remove the red background? An error icon would be better than making it all red. Also, let's make sure that the error detail is scrollable when it's very big.

**Comment by bekand** [comment]
Does this look good? I plan to add scrolling inside the red border part

image

**Comment by bekand** [comment]
bottom bar: only the summary
image
opened modal: summary  and actual technical error inside
image

**Comment by stephengoldbaum** [comment]
That looks cool.  Could we tone down the red so it's a bit less alarming (unless it actually is the IR, in which case nothing would work).

**Comment by nwokafor-choongsaeng** [comment]
Maybe we can have levels with different colors.
Like a 
- yellow: non-critical error/warning
- red: critical error

Then we classify all error messages into levels and display the classified error with it's appropriate applied color scheme.

**Comment by bekand** [comment]
warning: 
image
image

Error:
image
image

**Review by AttilaMihaly — APPROVED** [review]

**Pull request merged**
